version: '2'

services:
  pw-tests:
    container_name: playwright-tests
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        - CI=true
        - BASE_URL=${BASE_URL}
        - API_URL=${API_URL}
        - HTTP_CREDENTIALS_USERNAME=${HTTP_CREDENTIALS_USERNAME}
        - HTTP_CREDENTIALS_PASSWORD=${HTTP_CREDENTIALS_PASSWORD}
    volumes:
      - ./playwright-report:/plawright-tests/playwright-report
#    depends_on:
#      - mysql

#  mysql:
#    image: mysql:5.7
#    container_name: mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: test
#    ports:
#      - "3306:3306"
#    restart: on-failure