name: "Automated API and E2E tests (Playwright)"

on: push

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - name : "Checkout to tests repository"
        uses: actions/checkout@v4
        with:
         repository: ${{github.repository}}
         ref: ${{github.ref}}
      - name: "Copy env variables"
        run: |
          cp '.env.example' '.env'
      - name: "Run tests"
        env:
          BASE_URL: 'https://qauto.forstudy.space/'
          API_URL: 'https://api.qauto.forstudy.space/'
          HTTP_CREDENTIALS_USERNAME: 'guest'
          HTTP_CREDENTIALS_PASSWORD: 'welcome2qauto'
        run: |
          docker-compose up
      - name: "Upload report to artifacts"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: playwright-report/
          retention-days: 3
